project-excludes = [
    "**/tests/",
    "**/.tmp/",
    "**/.venv/",
    "*.ipynb",
    "**/typy_protocol/**",
    "**/typy_generic/**"
]
ignore-missing-imports = ["*"]
untyped-def-behavior = "skip-and-infer-return-any"
